### ISSUE TITLE
Document Qt version requirement (>=5.7)

### ISSUE THREAD

**Issue by bcampbell** [limetext/qml-go#4]
I think Qt5.7 is now required. I've got Qt5.5.1 installed, and my build fails with:

```
...src/github.com/limetext/qml-go/cpp/capi.cpp:215:5: error: ‘setDesktopFileName’ is not a member of ‘QGuiApplication’
```

Looks like the [desktopFilename](http://doc.qt.io/qt-5/qguiapplication.html#desktopFileName-prop) property was added to `QGUIApplication` in 5.7.

**Comment by ricochet1k** [comment]
setDesktopFileName has been removed for now. 0d03159d0ed45f668e00c79034d1a244fb3e2c0a
