### ISSUE TITLE
go 1.8 patch fix build, tests don't run

### ISSUE THREAD

**Issue by lassade** [limetext/qml-go#8]
With this little patch you will be able to compile it for go 1.8, lime-qml starts but I still getting the same errors as before with go 1.6 and 1.7.
```diff
index 99a284a..7846bb3 100644
--- a/bridge.go
+++ b/bridge.go
@@ -80,12 +80,11 @@ func RunArgs(args []string, f func() error) error {
        argv := make([]*C.char, argc+1)
        for i := 0; i < argc; i++ {
                argv[i] = C.CString(args[i])
+               defer C.free(unsafe.Pointer(argv[i]))
        }
        argv[argc] = nil

-       argvP := unsafe.Pointer(&argv[0])
-
-       C.newGuiApplication(C.int(argc), argvP)
+       C.newGuiApplication(C.int(argc), (**C.char)(&argv[0]))
        C.idleTimerInit((*C.int32_t)(&guiIdleRun))
        done := make(chan error, 1)
        go func() {
```
Here is the fun part I'm getting the `panic("cannot setup qml package for testing")` from `testing.go:69`, `/cdata` tests PASS with no errors.

Right now I will switch back to go 1.7 and keep trying sort out this issue: limetext/qml-go#7

**Comment by zoli** [comment]
tracking this issue on https://github.com/limetext/qml-go/issues/9, also I added a simple patch that works for me.
